apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: myPod
    type: proxy
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        # volumeMounts:
        # - mountPath: /data
        #   name: data
    # livenessProbe:
    #   httpGet:
    #     path: /_status/healthz
    #     port: 5000
    #   initialDelaySeconds: 90
    #   timeoutSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /_status/healthz
    #     port: 5000
    #   initialDelaySeconds: 30
    #   timeoutSeconds: 10
    # env:
    # - name:  ENVVARNAME
    #   value:  ENVVARVALUE
