apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-name
  labels:
    name:  my-name
spec:
  replicas: 3
  selector:
    matchLabels:
      os: ubuntu
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        os:  ubuntu
    spec:
      containers:
      - image:  ubuntu:latest
        name:  my-name
        resources:
          limits:
            cpu: "500m"
            memory: "500m"      
        ports:
        - containerPort:  80